"""create tables

Revision ID: 6ebfbea2560f
Revises: 
Create Date: 2026-07-05 00:13:55.259667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebfbea2560f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customerID', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('SeniorCitizen', sa.Integer(), nullable=True),
    sa.Column('Partner', sa.String(length=10), nullable=True),
    sa.Column('Dependents', sa.String(length=10), nullable=True),
    sa.Column('tenure', sa.Integer(), nullable=True),
    sa.Column('PhoneService', sa.String(length=30), nullable=True),
    sa.Column('MultipleLines', sa.String(length=30), nullable=True),
    sa.Column('InternetService', sa.String(length=30), nullable=True),
    sa.Column('OnlineSecurity', sa.String(length=30), nullable=True),
    sa.Column('OnlineBackup', sa.String(length=30), nullable=True),
    sa.Column('DeviceProtection', sa.String(length=30), nullable=True),
    sa.Column('TechSupport', sa.String(length=30), nullable=True),
    sa.Column('StreamingTV', sa.String(length=30), nullable=True),
    sa.Column('StreamingMovies', sa.String(length=30), nullable=True),
    sa.Column('Contract', sa.String(length=50), nullable=True),
    sa.Column('PaperlessBilling', sa.String(length=10), nullable=True),
    sa.Column('PaymentMethod', sa.String(length=50), nullable=True),
    sa.Column('MonthlyCharges', sa.Double(), nullable=True),
    sa.Column('TotalCharges', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('customerID')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('prediction', sa.String(length=20), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('customers')
    # ### end Alembic commands ###
