"""Создание теблиц для пользователей и предсказаний

Revision ID: b660cb0b156c
Revises: 
Create Date: 2026-07-04 00:46:41.433619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b660cb0b156c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customerID', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('SeniorCitizen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Partner', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('Dependents', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('tenure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PhoneService', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('MultipleLines', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('InternetService', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('OnlineSecurity', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('OnlineBackup', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('DeviceProtection', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('TechSupport', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('StreamingTV', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('StreamingMovies', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('Contract', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('PaperlessBilling', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('PaymentMethod', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('MonthlyCharges', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('TotalCharges', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customerID', name=op.f('customers_pkey'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('risk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('prediction', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('predictions_pkey'))
    )
    # ### end Alembic commands ###
